### ISSUE TITLE
Disable video thumbnail previews

### ISSUE THREAD

**Issue by jockehaddock** [webex/webex-js-sdk#1136]
I cant find any settings to disable the video preview thumbnails with corresponding name string presented automatically at the bottom of the remote videofeed. 

It is managed automatically and appears when switching between multiple speakers and their videofeeds.

Is it possible to disable this behavior and perhaps manage other behaviours as well when using the JS SDK?

**Comment by judupree** [comment]
Hello - project management is asking if you could provide any business usecase associated with the need to disable the video preview?

**Comment by olivierproffit** [comment]
@jockehaddock it's not possible today but I would love to here your use case to prioritize the required modification accordingly. thanks
