### ISSUE TITLE
Expose api on the Call interface to change device during a meeting 

### ISSUE THREAD

**Issue by CapOM** [webex/webex-js-sdk#1168]
It is possible to set the devices before starting the call through the api: `activecall.phone.dial(roomId, dialOpts)` .The dialOpts contains the device id using MediaStreamConstraints as described in the standard Web MediaStream API https://www.w3.org/TR/mediacapture-streams/ .

Too do the same but after the call is started there is 2 options:

1. `activecall.media.setMedia('video', direction, newConsraints)`
The problem is that direction depends on an internal function boolToStatus.

2. `activecall.media.addOrReplaceTrack(stream.getVideoTracks()[0]);`
The problem is that this function is marked private and expect that we call getUserMedia ourself. 

So that would be great to add new apis `activecall.setAudioInputDeviceId(deviceId)` and `activecall.setVideoInputDeviceId(deviceId)` or similar. Thx!

**Comment by lak-16** [comment]
Hi, even am looking for something like this. When I have multiple cameras connected to my system, i want to make use of camera which was used for last call. Am not able to set before call start or after call start.

activecall.media.setMedia('video', direction, newConsraints)
above also didn't work for me.

**Comment by judupree** [comment]
Per engineering, this should be resolved by this pull request:

https://github.com/webex/webex-js-sdk/pull/1251
