### ISSUE TITLE
Links to local sample apps are broken

### ISSUE THREAD

**Issue by tahanson-cisco** [webex/webex-js-sdk#1177]
## Expected Behavior
Links to local sample apps should be in the format:
https://localhost:8000/browser-auth-implicit/

## Current Behavior
Links take you to: https://localhost:8000/packages/node_modules/samples/browser-auth-implicit
Which results in 404

## Possible Solution (we welcome any logical suggestion)

Change the links 

## Steps to Reproduce
1. Click on any of the "local app" links here: https://github.com/webex/spark-js-sdk

## Environment Details

TAHANSON-M-Q12S:spark-js-sdk tahanson$ node -v
\v12.1.0
TAHANSON-M-Q12S:spark-js-sdk tahanson$ npm -v
6.9.0

**Comment by mattnorris** [comment]
Please see https://github.com/webex/webex-js-sdk#samples
