### ISSUE TITLE
The UMD build is broken

### ISSUE THREAD

**Issue by EmilNordling** [webex/webex-js-sdk#1192]
## Expected Behavior
Loading the ciscospark.min.js should not cause an error. 

## Current Behavior
Unfortunately I don't have the luxury to work with a standardized bundler, like webpack, on the project where I'm implementing Webex. Instead the project is going to be dependent on the prebuilt script. However, when the prebuilt script is being executed it'll fail on a line where an undefined object is trying to access a `SparkPlugin` property on itself. This error causes the ciscospark instance to never successfully initialize and will not be reachable on the window object.

![image](https://user-images.githubusercontent.com/8842821/58799407-912b4000-8605-11e9-8627-e58198c4e39b.png)

## Possible Solution (we welcome any logical suggestion)
Not really a solution but:

I've tested the lib in a normal project setup with webpack, and when the lib is targeting to use `dist/index.js` or the `src/index.js` it'll works. But never when using the UMD. But there must be something in the way it's being bundled that causes this error?

## Steps to Reproduce
1. Create an html file with a script element that loads in the newest version of the UMD build.
2. Open said html file in a browser.
3. ciscospark failed to initialize.

Here's a fast copypasta to reproduce from:
```HTML
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>cisco test</title>
    <script type="text/javascript" src="./ciscospark.min.js"></script>
  </head>
  <body></body>
</html>
```

## Environment Details
Version of ciscospark: `v1.58.6`
Browser: `Chrome 74.0.3729.169`

**Comment by Maximus325** [comment]
Like @EmilNordling  I won't be using a bundler. I have tried using previous versions of the min.js file but it appears this hasn't been working for some time. Can anyone provide an update?

Thanks

**Comment by EmilNordling** [comment]
> Like @EmilNordling I won't be using a bundler. I have tried using previous versions of the min.js file but it appears this hasn't been working for some time. Can anyone provide an update?
> 
> Thanks

The way we got around this was to prebundle Webex through Browserify (rollup does not seem to work) in the same fashion as their documentation. If you follow the steps at: https://developer.webex.com/docs/sdks/browser

Then put the bundle file that Browserify produced on the server / CDN.

But the .min.js file should still be fixed to work imo.

**Comment by Maximus325** [comment]
Thanks @EmilNordling ! Worked perfectly

**Comment by adamweeks** [comment]
This should be resolved with the `webex.min.js` file.
