### ISSUE TITLE
Toggling video breaks after multiple toggles

### ISSUE THREAD

**Issue by robgonnella** [webex/webex-js-sdk#1202]
## Expected Behavior
When dialing & connecting via SIP address, toggling the video on and off multiple times should result in the remote video being muted and unmuted appropriately.

## Current Behavior
Toggling video may work as expected once or twice but eventually the remote user will see a permanently muted video from that participant. The local stream will show the video freezing and resuming but on the remote side it just gets stuck in a muted state. Watching the logs in the devtools console, it seems like locus gets stuck expecting a different direction.

## Steps to Reproduce
Steps to repro can be found here: https://github.com/robgonnella/ciscospark-av-issue-repro

## Environment Details
All environment details in above link

**Comment by CapOM** [comment]
Same issue with latest webex v1.60.2, i.e. "activeCall.toggleSendingVideo()" fails after calling it a few times.

**Comment by taymoork2** [comment]
So we're gonna be deprecating `plugin-phone` soon and we're replacing it with `plugin-meetings`.
We're finalizing docs and an upgrade guide to help out, which should be done in a week.

**Comment by olivierproffit** [comment]
@CapOM  @robgonnella  did you try with `plugin-meetings ` ?
https://js.samples.s4d.io/browser-plugin-meetings/
https://github.com/webex/webex-js-sdk/blob/master/packages/node_modules/%40webex/plugin-meetings/UPGRADING.md
