### ISSUE TITLE
Device registration sends an empty string with space. This is because process.title is that on nodejs

### ISSUE THREAD

**Issue by var-kar** [webex/webex-js-sdk#1221]
```
process.title = ' ';
```
notice the space. 

```
name: process.title || inBrowser && 'browser' || 'javascript',
```
the above line on packages/node_modules/@webex/internal-plugin-wdm/src/config.js

sends empty name with space for the https://wdm-a.wbx2.com/wdm/api/v1/devices

It happens only if I use the SDK on nodejs. The API rejects the call. So the whole SDK is not very usable ATM on nodejs backend.

This happens only when the node js is run using some thirdparty terminal. eg. GIT BASH on Windows. 

Hope it helps. Quick fix would help.

Many thanks,
Karthik

**Comment by InteractiveTimmy** [comment]
We were able to reproduce similar results as described when attempting to run the SDK via various Windows terminals, such as PowerShell and GitBash. While we work towards resolving this issue, a quick fix that may work in your use case is to hard-code `process.title` to be equal to `node`:

```javascript
process.title = 'node';
```
`node` is the value that is given to `process.title` when running the SDK on standard Unix terminal emulators.
