### ISSUE TITLE
@webex/plugin-meetings disconnects after a few seconds if receiveShare = false

### ISSUE THREAD

**Issue by jnetterf** [webex/webex-js-sdk#1253]
## Expected Behavior
The remote media stream should not hang a few seconds when joining a meeting then calling:
```
await meeting.addMedia({
  mediaSettings: {
    receiveVideo: true,
    receiveAudio: true,
    receiveShare: false, // <-- does not hang with this set to true
    sendVideo: false,
    sendAudio: false,
    sendShare: false,
  },
  localStream: null,
  localShare: null,
});
```

## Current Behavior
The remote media stream hangs a few (variable, 5-30) seconds when joining a meeting then calling:
```
await meeting.addMedia({
  mediaSettings: {
    receiveVideo: true,
    receiveAudio: true,
    receiveShare: false, // <-- does not hang with this set to true
    sendVideo: false,
    sendAudio: false,
    sendShare: false,
  },
  localStream: null,
  localShare: null,
});
```

## Possible Solution (we welcome any logical suggestion)
I do not know the cause of this defect.

## Steps to Reproduce
1. Go to https://js.samples.s4d.io/browser-plugin-meetings in Firefox or Chrome.
2. Have at least one active meeting. (I went to bluescape.webex.com, created a meeting at the current time, and started it).
3. Enter a valid auth token under credentials and click "Connect"
4. Click "Sync Meeting"
5. Deselect `receiveShare`, and make sure receiveVideo, receiveAudio, and at least one send stream are selected (if no send streams are selected, getMediaStreams will fail, and the stream won't start at all)
5. Connect to that meeting somewhere else and set up a video feed so you can tell when the video in the sample hangs
6. Click "JOIN WITH MEDIA" beside the meeting that popped up.
7. Observe that the video feed works for a few seconds, and then hangs. On my iPad, with the Webex Meet app,  the text "Joshua has left the meeting" appears briefly. In my console, I see the error "ICE failed, add a STUN server and see about:webrtc for more details", but I suspect that is a red herring.

## Environment Details
I see this issue in an app I am working on with the following dependencies:
```
    "@webex/internal-plugin-wdm": "1.66.2",
    "@webex/plugin-authorization": "1.66.2",
    "@webex/plugin-device-manager": "1.67.1",
    "@webex/plugin-meetings": "1.67.0",
    "@webex/webex-core": "1.66.2"
```

The issue can also be reproduced at https://js.samples.s4d.io/browser-plugin-meetings.

**Comment by WenboL** [comment]
Tested with release v1.80.47, seems we no longer can reproduce this issue.
