### ISSUE TITLE
@webex/plugin-meetings spams console.log

### ISSUE THREAD

**Issue by jnetterf** [webex/webex-js-sdk#1254]
## Expected Behavior
I expect to not see anything in my console when successfully using the API to join a meeting, unless I change the config to increase the logging level.

## Current Behavior
There a bunch of logs that start with "LOCUS EVENT" or "ICE CHANGE"

## Possible Solution (we welcome any logical suggestion)
Use the super fancy `@webex/plugin-logger` package instead of console.log, especially in the following two places:
 - https://github.com/webex/webex-js-sdk/blob/d0441388bcf6d16934a37af8e670cbf630e1e1c7/packages/node_modules/@webex/plugin-meetings/src/meetings/index.js#L143
 - https://github.com/webex/webex-js-sdk/blob/d0441388bcf6d16934a37af8e670cbf630e1e1c7/packages/node_modules/@webex/plugin-meetings/src/meeting/util.js#L552

Enforce that console.log isn't used with [an eslint rule](https://eslint.org/docs/rules/no-console)

## Steps to Reproduce
1. Go to https://js.samples.s4d.io/browser-plugin-meetings/
2. Start or join a meeting.
3. Open your developer console and see all the logs.

## Environment Details
This is reproducible with `@webex/plugin-meetings` v1.67.0, and on https://js.samples.s4d.io/browser-plugin-meetings/

**Comment by adamweeks** [comment]
This has been resolved with the `LoggerProxy` within the meetings plugin.
