### ISSUE TITLE
@webex/plugin-meetings: leave() should not cause an uncaught error to be thrown

### ISSUE THREAD

**Issue by jnetterf** [webex/webex-js-sdk#1257]
## Expected Behavior
Calling meeting.leave() on a joined meeting should never cause an exception to be thrown.

## Current Behavior
If I join a meeting and set the media directions to sendAudio, sendVideo, receiveAudio, receiveVideo, and receiveShare, and then call `meeting.leave()`, I get the following error:

```
InvalidAccessError: track must be associated with a unique sender or receiver, but  is associated with 0 senders and 0 receivers.
```

## Possible Solution (we welcome any logical suggestion)
I have no idea.

## Steps to Reproduce
1. Go to https://js.samples.s4d.io/browser-plugin-meetings/
2. Authenticate
3. Create a meeting with a start time in the past and an end time in the future.
4. Click "Sync meeting"
5. Check at least  sendAudio, sendVideo, receiveAudio, receiveVideo, and receiveShare
6. Click "START WITH MEDIA" on a meeting
7. Click leave()
8. See error in console.

## Environment Details
I can repro this with the following versions:
```
    "@webex/internal-plugin-wdm": "^1.66.2",
    "@webex/plugin-authorization": "^1.66.2",
    "@webex/plugin-device-manager": "^1.67.1",
    "@webex/plugin-meetings": "^1.67.0",
    "@webex/webex-core": "^1.66.2"
```

It's also reproducible with https://js.samples.s4d.io/browser-plugin-meetings/

**Comment by adamweeks** [comment]
@jnetterf sorry we missed this ticket, I'm not able to reproduce the issue on the latest version. Please reopen the ticket with reproduction steps if the issue still exists.
