### ISSUE TITLE
webex.phone used in official docs. function not found in my webex object

### ISSUE THREAD

**Issue by levensailor** [webex/webex-js-sdk#1269]
## Expected Behavior
Using the docs below, it seems like I could do `webex.phone.register()`
https://webex.github.io/webex-js-sdk/guides/calling/

## Current Behavior
I don't see a webex.phone at all

## Possible Solution (we welcome any logical suggestion)
it seems webex.internal.device.register() works

## Environment Details
SDK Version "1.72.3"

**Comment by J5Dev** [comment]
Depends what version you are using... We have just discovered this as well.

Currently we are on Version 1.67.1
Seems the latter versions (latest being 1.75.1 has completely removed the use of phone & call, and instead replaced it with using the meeting object.

Essentially, they have introduced a huge breaking change, with little to no warning either written or by way of the version number!!

Factor in the usual 'issue' with docs being what they are, and you have the situation you and I now find ourselves in.

The solution it seems, is to look to the samples and hope you can figure out the use of the meeting object :/

**Comment by mattnorris** [comment]
@levensailor @J5Dev I apologize for the confusion. `webex.phone` is no longer the default, though you can use it with SDK versions 1.6x or by creating a custom build. 

`webex.meetings` delivers a better meeting (call) experience with tighter integrations across Webex products and devices. Follow our [upgrade guide](https://github.com/webex/webex-js-sdk/blob/master/packages/node_modules/%40webex/plugin-meetings/UPGRADING.md) and look at our [samples](https://github.com/webex/webex-js-sdk/blob/master/packages/node_modules/samples/browser-multi-party-call/app.js) to include it in your application. 

Regarding https://webex.github.io/webex-js-sdk/guides/calling/ - this is outdated and will be corrected. 

If you have any questions about `webex.meetings` or custom builds, please let us know.
