### ISSUE TITLE
RefreshCallback is not called

### ISSUE THREAD

**Issue by antonkarsten** [webex/webex-js-sdk#1347]
I use the authorization grant flow. So my node server stores the webexTokens. When my browser application starts it retrieves the webex access_token from the server. and I run the following code in the browser
```
        this.webex = window.webex = Webex.init({
          credentials: {
            access_token: this.access_token,
            refreshCallback: () => {
              return this.getRefreshToken();
            }
          }
        });
```
everything works fine. But after the access_token expires and the next api call is made (with the sdk) I get a 401 (Unauthorized) response but the refreshCallback is not called (as I expected).
 
## Environment Details
* SDK Version 1.80.5
* Browser Version Chrome Version 76.0.3809.132 (Official Build) (64-bit)
* Node version 10.11.0
* NPM Version 6.9.0

**Comment by InteractiveTimmy** [comment]
Hello,

We are currently looking into the cause of this error. To confirm, has this functionality worked prior to version SDK Version 1.80.5?

**Comment by antonkarsten** [comment]
@InteractiveTimmy I am new to the SDK, I dont know if it worked before. I just expected the callback to be called. Thank you for looking in to it

**Comment by akoushke** [comment]
@antonkarsten  I don't think you are invoking the method properly. Take a look at this example:

```js
const webex = window.webex = new WebexCore({
  config: {
    credentials: {
      refreshCallback(webex, token) {
        return webex.request({
          method: 'POST',
          uri: '/refresh',
          body: {
            // eslint-disable-next-line camelcase
            refresh_token: token.refresh_token
          }
        })
          .then((res) => res.body);
      }
    }
  }
});
```

**Comment by akoushke** [comment]
I don't see anything wrong here. feel free to re-open if you have any other questions.
