### ISSUE TITLE
Screensharing quality degradation

### ISSUE THREAD

**Issue by WenboL** [webex/webex-js-sdk#1419]
## Expected Behavior
Screensharing functionality should work properly with high quality and fast performance.

## Current Behavior
Screen sharing quality will drop greatly after certain period of time and will take relatively long time to recover. During this time, nothing is readable. All the viewer that viewing the streamer's screen will have the same bad image quality.

I am providing two sample videos and one Readme file to explain the situation. Link:
https://silveravenue-my.sharepoint.com/:f:/g/personal/wenbo_liu_bluescape_com/EiTWRYIxwDFGm0D45gnSoxwBwyy6UmiQLPfv5unSaN2Ljg?e=SzGZqE

All the videos are having the same arrangement, which left side is our application using Webex JS SDK, right top is Webex Teams, right bottom is Webex Meetings.
- Videos are recorded in different network environments, both recorder and streamer. So this is not relevant to network.
- The streamer is using Windows OS with 4k native resolution and streaming from our product which is using Webex js SDK.

## Possible Solution (we welcome any logical suggestion)

If streamer is sharing screen by using Webex meeting app, it works properly. Same network, same time, same environment. 

Is there any thing special/or tricks we need to do while preparing the local sharing media stream?

## Steps to Reproduce

```
       const [_, localShareStream] = await this.meeting.getMediaStreams({
          sendAudio: false,
          sendVideo: false,
          sendShare: true,
        });

        await this.meeting.updateShare({
          sendShare: true,
          receiveShare: true,
          stream: localShareStream,
        });
```

The issue is easily reproducible by using 4k resolution and going through browser pages slowly.
 
1. Start screen sharing using webex js sdk
2. Stay on one white background browser page for couple minutes without moving
3. Move slightly without totally updating the page
4. Video will become bad

## Environment Details

* SDK Version: 1.80.45
* Node/Browser Version Node:12.10, browser: Chrome Version 78.0.3904.97 (Official Build) (64-bit)
* OS Windows
* Streamer screen resolution: 4k native

**Comment by WenboL** [comment]
This issue is mostly visible when user is sharing some browser page such as Jira page which is mostly white background and have tables, words on it.

**Comment by WenboL** [comment]
I assume the screenshare quality is improved? Since it closed without any info. Will verify

**Comment by adamweeks** [comment]
Sorry @WenboL, we are tracking internally the quality improvements and no longer using github issues. Feel free to reach out.
