### ISSUE TITLE
Unhelpful error message initializing with invalid access token

### ISSUE THREAD

**Issue by dstaudt** [webex/webex-js-sdk#1434]
## Expected Behavior
init() with an invalid access token would ideally result in an immediate error with a message making the nature of the problem clear

## Current Behavior
A delay of ~30 seconds followed by the following unhelpful error:

```
(node:32414) UnhandledPromiseRejectionWarning: Error: services: timeout occured while waiting for 'postauth' catalog to populate
    at Timeout._onTimeout (/home/dstaudt/Downloads/bk/sdk-test/node_modules/@webex/webex-core/dist/lib/services/service-catalog.js:349:9)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:32414) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
```

## Possible Solution (we welcome any logical suggestion)
Perhaps the auth failure condition can be better detected via the unhandled promise rejection mentioned in the error..?

## Steps to Reproduce
```javascript
const Webex = require(`webex`);
const webex = Webex.init({
  credentials: {
    access_token: 'invalid'
  }
});
webex.rooms.create({ title: `My First Room` });
```

## Environment Details

* SDK Version: v1.80.58
* Node/Browser Version: v10.15.0
* NPM Version: 6.12.0

**Comment by adamweeks** [comment]
Thanks for the feedback, we are adding this to our feature list.
