### ISSUE TITLE
meeting.UpdateShare() will set isVideoMute to false

### ISSUE THREAD

**Issue by WenboL** [webex/webex-js-sdk#1449]
## Expected Behavior

By calling 'meeting.UpdateShare()' we expect the specific member's property 'isContentSharing' is set to true only. 'isAudioMuted' and 'isVideoMuted' should stay unchanged.
## Current Behavior

if current 'member.isVideoMuted = true',  'meeting.UpdateShare()' always update Participant himself's 'member.isVideoMuted' to false.

## Possible Solution (we welcome any logical suggestion)

We receive two 'members:update' events locally after calling 'meeting.updateShare()' which first one set member.isVideoMuted to false. Then second one will set 'member.isContentSharing' to true. Not sure why first one is been triggered. Maybe it is the reason what setting isVideoMuted to false. 

## Steps to Reproduce

1. Mute user camera and mic so the member object from meeting.getMembers() has 'isVideoMuted' and 'isAudioMuted' set to true.
2. Start screen sharing by calling 
``` Javascript       
       const [_, localShareStream] = await this.meeting.getMediaStreams({
          sendAudio: false,
          sendVideo: false,
          sendShare: true,
        });

        await this.meeting.updateShare({
          sendShare: true,
          receiveShare: true,
          stream: localShareStream,
        });
```
3. The same member object from this.meeting.getMembers() will have isVideoMuted set to false.

## Environment Details

* SDK Version 1.80.65

**Comment by adamweeks** [comment]
Unable to reproduce as of 1.80.86. `isVideoMuted()` and `isAudioMuted()` accurately describes the state after running `updateShare`.

**Comment by WenboL** [comment]
Hi Adam, 

Thank you for taking a look on this issue. However, I did a quick verification on release 1.80.86 I am still seeing this issue happening. 

Key points are we init meeting with sendVideo = false and videoStream = null also User need to enable video first then mute the video. Then when the same user is sharing, his isVideo muted status will become to false and stays at false even after sharing finished.

In the log image attached, the logs between 'Start***' and 'End***' are printed during 'members:update' event. 
<img width="883" alt="screenshare1" src="https://user-images.githubusercontent.com/5519735/72754005-9ccb7700-3b94-11ea-9e05-da1d18398a6a.png">
The log above is a good case where user 'wliu wliu' shares and stops sharing, his isVideoMuted stays at true all the time. 

<img width="901" alt="screenshare2" src="https://user-images.githubusercontent.com/5519735/72754347-88d44500-3b95-11ea-9931-bbb67333958a.png">
The second log file above shows:

1. user wliu wliu starts video, then stops video
2. user wliu wliu starts sharing, there were two 'members:update' event first set isVideoMuted to false, then set 'isContentSharing' to true
3. after user wliu wliu stops sharing, 'isVideoMuted' stays at false, which is incorrect.

**Comment by arun3528** [comment]
@WenboL shouldn't the video be in mute state because you just did share and unshare which is a separate stream
