### ISSUE TITLE
Logging Proposal for plugin-logger

### ISSUE THREAD

**Issue by chrisadubois** [webex/webex-js-sdk#1467]
SDK Logging Proposal

Current State
SDK wraps the console logs, and sends its own logs to a buffer, and sends consumers of the SDK logs to the same buffer. This buffer size is limited by a config value in plugin-logger which defaults to 1000 submissions. The logs get submitted through plugin-support and send to the client logs service.

Requirements
Clients of the SDK can differentiate their logs from SDK logs.

Proposal
A new configuration value, clientBufferSize is added to plugin-logger
A new configuration value, clientLevel is added to plugin-logger
Plugin-logger gets a new series of levels and wrapped console methods, prefixed with ‘client’
(which means no code changes for any consumers of the SDK today except those who want to use the new buffer, i.e., web-client)
Plugin-logger prefixes all SDK logs with ‘wx-js-sdk:’ and prefixes all client logs with ‘client:’ so that eventually we can coalesce the time periods once we have a streaming log service for javascript clients in cisco
Plugin-support or plugin-logger formats the buffers for client log submission “better” – this is an unknown
Plugin-support adds a new configuration value, logSubmission, which can be set to ‘client’, ‘sdk’, or ‘both’
Plugin-support combines the two buffers for submission to clientlogs (atlas) service, noting them as different based on the configuration value

**Comment by adamweeks** [comment]
@chrisadubois proposal is good, feel free to begin work
