### ISSUE TITLE
meetings.register() method never resolves promise

### ISSUE THREAD

**Issue by smgdesign** [webex/webex-js-sdk#1510]
## Expected Behavior
Calling `webex.meetings.register()` should resolve / reject
## Current Behavior
`register()` promise sits pending, with logging enabled the following error is returned:
```
mercury: connection attempt failed Error: No service associated with url: [wss://mercury-connection-k.wbx2.com/v1/apps/wx2/registrations/932e6657-a1a6-4872-bc13-81885ddf746b/messages]
    at child.convertUrlToPriorityHostUrl (services.js?6600:635)
    at eval (mercury.js?55f0:194)
    at async Promise.all (:3000/index 0)
```

## Possible Solution (we welcome any logical suggestion)
Think I've missed a configuration option somewhere and it's connecting to an old endpoint.

## Steps to Reproduce
1. Initialise webex with
```
window.webex = initWebex({
  config: {
    meetings: {
      deviceType: 'WEB',
    },
  },
})
```
2. Enable info logging `window.webex.config.logger.level = 'info'`
2. Check registered with `window.webex.meetings.registered`
3. Call the register method `const registration = window.webex.meetings.register()`
4. Observe the `registration` variable and view console for errors

## Environment Details

* SDK Version: 1.80.113
* Node/Browser Version: Chrome 79.0.3945.130
* NPM Version: 6.13.6

**Comment by smgdesign** [comment]
Further investigation reveals the access token is the issue.
If a personal access token is provided, instead of using a JWT then meeting registration resolves.
It would appear that authenticating a guest user results in being unable to register to the meetings SDK. I'm assuming this is a general limitation, but the promise should at least reject instead of hanging

**Comment by smgdesign** [comment]
This is resolved, but the documentation should be clearer.
When authenticating as a guest user using JWT, you have to create a guest access token and initialise the SDK using the access token, not the JWT in order for device registration to work.
The documentation here: https://developer.webex.com/docs/guest-issuer#using-guest-tokens claims that when using the SDK it handles conversion of JWT to tokens for you. This is not currently the case.

**Comment by adamweeks** [comment]
@smgdesign are you calling `requestAccessTokenFromJwt` as described on that page? You should have a valid access token after that and able to call `meetings.register()` like so:

```js
webex.authorization.requestAccessTokenFromJwt({jwt: token})
      .then(() => {
        // the user is now authenticated with a guest token (JWT)
        // proceed with your app logic
        return webex.meetings.register();
      })
```

**Comment by adamweeks** [comment]
Verified that the code is properly erroring:

```js
webex = Webex.init({
  config: {
    meetings: {
      deviceType: 'WEB'
    }
  }
});

webex.meetings.register().catch((e) => console.error(e));
```
Prints the following error:

>Error: SDK cannot authorize

**Comment by smgdesign** [comment]
Apologies, didn't see the replies. I was calling `requestAccessTokenFromJwt` but I don't think I was waiting for it to resolve before calling the `.register()` command.

**Comment by smgdesign** [comment]
I'll try to recreate the scenario and provide some code as there was definitely a set of steps that prevented `.register()` from resolving / rejecting the promise and caused an endless loop of `mercury connection failed` logs.
