### ISSUE TITLE
Feature Request: Proxy Support

### ISSUE THREAD

**Issue by rkennel** [webex/webex-js-sdk#1518]
Problem: 
Many companies that use webex teams are behind a corporate proxy.  I have not discovered any documentation or see evidence in the source code (although I have not browsed all of the code) as to a mechanism to configure a https proxy.

Solution:
Provide a configuration attribute that accepts proxy configuration parameters

**Comment by adamweeks** [comment]
Please contact developer support at https://developer.webex.com/support for further assistance with this issue.
