### ISSUE TITLE
Create message doesn't support adaptive cards

### ISSUE THREAD

**Issue by amankhoza** [webex/webex-js-sdk#1547]
## Expected Behavior

I expect adding a parameter 'cards' with the stringified json for the adaptive card should work.

## Current Behavior

There doesn't seem to be support for sending a card using create message.

## Possible Solution (we welcome any logical suggestion)

Example:  
```
let redirect_uri = `${window.location.protocol}//${window.location.host}`;
if (window.location.pathname) {
  redirect_uri += window.location.pathname;
}
```
## Steps to Reproduce

1.
2.
3.
4.

## Environment Details

* SDK Version
* Node/Browser Version
* NPM Version

**Comment by jpjpjp** [comment]
Hi @amankhoza , the message object field isn't "cards" it's "attachments" as described in the [Buttons and Cards Developers Guide](https://developer.webex.com/docs/api/guides/cards).  You must pass an array that consists of a single, well defined, adaptive card object.

Here is an example of using the SDK to post a card.  Assume "webex" is a properly created instance of the Webex SDK and that "roomId" is the ID of a space that the SDK user is a member of:

```js
        const attachment = {
          contentType: 'application/vnd.microsoft.card.adaptive',
          content: {
            type: 'AdaptiveCard',
            version: '1.0',
            body: [
              {
                type: 'TextBlock',
                text: 'This is a really simple card'
              }
            ]
          }
        };
       webex.messages.create({
            roomId: room.id,
            text: "If you see this your card did not render.",
            attachments: [attachment]
          })
```

Does this resolve your issue?

**Comment by amankhoza** [comment]
Oops don't know where I got 'cards' from, attachments worked thanks :)
