### ISSUE TITLE
Ability to join a meeting without sharing anything

### ISSUE THREAD

**Issue by guillaumepotier** [webex/webex-js-sdk#1561]
Hi there,

My use case is quite straight forward: I want to integrate a Webex Meeting in my application, but just in an unidirectional way, only the "presenter" shares its audio/video/screen, and joining users are guests on my website (like a webinar/live stream with no interaction features).

It seems not to be doable right now, it seems [here](https://github.com/webex/webex-js-sdk/blob/98b4659dc6a1c6306fab2108ea4bec042ee1bf84/packages/node_modules/@webex/plugin-meetings/src/meeting/index.js#L2104) that it is not allowed to join a meeting without sharing anything.

Can I ask why this actual restriction?

I might make joining users into mute audio/video mode, but their browser would ask for permissions although it is unneeded.

Thanks for your help

**Comment by guillaumepotier** [comment]
I currently use that piece of code that seems to work, and that avoids using `mute()`. I set the `sendAudio` or `sendVideo` to `true`, but in `meeting.addMedia()` I just simply do not add `localStream`:

```javascript
  return meeting.join().then(() => {
   // we are "forced" to use Audio and/or Video, although we won't pass it after
    const mediaSettings = {
      receiveVideo: true,
      receiveAudio: true,
      receiveShare: true,
      sendVideo: true,
      sendAudio: true,
      sendShare: false
    };

    return meeting.getMediaStreams(mediaSettings)
      .then(mediaStreams => {
       // only give mediaSettings, do not add localStream we do not want to share anything here
        meeting.addMedia({ mediaSettings });
      });
  });
```

It correctly join the Meeting, retrieve remote audio/video/sharing streams, and do not add local ones. Though, browser asks user for permission, and display a recording icon in the tab title which is not a really good experience.

**Comment by arun3528** [comment]
@guillaumepotier  if i am correct you just want one of the user to guest who just receives share audio video

Guest({receiveShare, reciveAudio , reciveVideo}) should be true and dont add any tracks. For sender

Make all send values to true and receive values to fails and add track

**Comment by Nayper** [comment]
The solution is simple 😃 
```
 private async joinMeeting(meeting) {

     meeting.on('media:ready', (media) => {
      if (!media) {
        return;
      }
      if (media.type === 'remoteVideo') {
        //
      }
      if (media.type === 'remoteAudio') {
       //
      }
      if (media.type === 'remoteShare') {
        //
      }
    });

    meeting.on('media:stopped', (media) => {
      if (media.type === 'remoteVideo') {
        //
      }
      if (media.type === 'remoteAudio') {
       //
      }
      if (media.type === 'remoteShare') {
        //
      }
    });

    const mediaSettings = {
      receiveVideo: true,
      receiveAudio: true,
      receiveShare: true,
      sendVideo: false,
      sendAudio: false,
      sendShare: false
    };

    await meeting.join();
    await meeting.addMedia({ mediaSettings });
}
```
