### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by sgtoj** [webex/webex-js-sdk#1564]
Please include a TypeScript generated declaration file with the npm package.

**Comment by adamweeks** [comment]
Thanks for your feedback! We are planning on adding this soon!

**Comment by next-franciscocalle** [comment]
Any updtes on this?

**Comment by lalli-flores** [comment]
@next-franciscocalle, no updates. This was just before the pandemic hit and since, our priorities have changed. No ETA on this.

**Comment by xharriscisco** [comment]
Although after looking through the source, it looks like there are lots of js comments for all the methods. Is it possible to generate typescript declaration files from this?

**Comment by csprocket777** [comment]
> Although after looking through the source, it looks like there are lots of js comments for all the methods. Is it possible to generate typescript declaration files from this?
> 
> Edit: It seems that `npx -p typescript tsc packages/node_modules/**/*.js --declaration --allowJs --emitDeclarationOnly --outDir types` can generate type declaration files. Not sure how this works with es6 importing but I will be investigating this a bit.

Were you successful with this approach?
