### ISSUE TITLE
Unable to join meeting on alpha site

### ISSUE THREAD

**Issue by ck123pm** [webex/webex-js-sdk#1567]
Hi, there

I'm using this SDK to integrate `webex meeting` and `webex teams's group meeting`. On *cisco.webex.com* and *go.webex.com*, everything works fine. However, it's unable to join the meeting held on *alpha.webex.com* with this SDK. Besides, meetings created on `webex teams` cannot be joined too. I think the reasons might be the same.

In addition, I tried the demo on https://js.samples.s4d.io/, but the result was the same as using the SDK.

## Expected Behavior

Join all the meetings normally.

## Current Behavior

Failed to join the meeting on `alpha.webex.com`.
It returns several errors such as 
`MeetingRequest->determineRedirections# failed to get locus details from url: https://locus.meet-a.prod.meetapi.webex.com/locus/api/v1/loci, reason: t: <!doctype html><html lang="en"><head><title>HTTP Status 401 – Unauthorized`

`GET https://locus-a.wbx2.com/locus/api/v1/loci/meetingInfo/127943581@webex.com?type=SIP_URI&useUriLookup=false&alternateRedirect=true 404 (Not Found)`

`POST https://locus.meet-a.prod.meetapi.webex.com/locus/api/v1/loci/c1bd04be-3d95-373e-90cb-5830c479da87/participant?alternateRedirect=true 401 (Unauthorized)`

## Possible Solution (we welcome any logical suggestion)

I tried teams's web client. By grabbing the packet, I see that authorization (i.e.AccessToken) is included in the header of this request `GET https://locus.meet-a.prod.meetapi.webex.com/locus/api/v1/loci`. But in the demo on https://js.samples.s4d.io/, I see that there is no authorization  in the header of this request, and then the request returns 401 Unauthorized. I don't know if it matters.

## Environment Details

* SDK Version `"webex": "^1.80.148",`

**Comment by adamweeks** [comment]
Hello @ck123pm thanks for opening the issue. Since you are connecting to an alpha site, the locus server it is using is not in the service catalog, so the sdk is removing the authentication header from the request. You will need to change the configuration when creating an sdk instance:

```js
const webex = Webex.init({
  config: {
    services: {
      validateDomains: true
    }
  }
});
```

**Comment by marecektn** [comment]
Hi!
I am trying to run the quick start project, however on join I am getting very similar responses:

`https://locus-a.wbx2.com/locus/api/v1/loci/meetingInfo/marek@********.com?type=SIP_URI&useUriLookup=false&alternateRedirect=true 404 (Not Found)`

init: 
`const webex = Webex.init({
  config: {
    services: {
      validateDomains: true
    }
  },
  credentials: {
    access_token: <<MY_ACCESS_TOKEN>>
  }
});`

webex version: 1.80.220
