### ISSUE TITLE
SDK size

### ISSUE THREAD

**Issue by guillaumepotier** [webex/webex-js-sdk#1614]
Hi there,

I'm using Parcel to build and ship my code for the browser, and here is what I'm using from my package.json

```
    "crypto-js": "^4.0.0",
    "moment": "^2.24.0",
    "urijs": "^1.19.2",
    "webex": "^1.80.147"
```

The Parcel build dist file weight (non minimzed) is 7Mo ! It is a bit crazy right? Do I miss something. The wexbex sdk is requiring many many sub deps, are they all mandatory for production usage?

Do I miss something here?

Thanks

**Comment by adamweeks** [comment]
HI @guillaumepotier thanks for opening the issue. We are aware that most of our sdk size is coming from our encryption tools usage. We are working to provide better tree-shaking ability to reduce the sdk size.
