### ISSUE TITLE
iOS Video Full Screen

### ISSUE THREAD

**Issue by nerdbaggy** [webex/webex-js-sdk#1664]
## Expected Behavior
I would like it if the video could be full screen when viewed in iOS. I'm not sure if it works in android or not.

## Current Behavior
There is no way to make the video full screen

## Possible Solution (we welcome any logical suggestion)
Not sure

## Steps to Reproduce
1. Try and watch the video in full screen

## Environment Details
* SDK Version: 1.80.207
* Node/Browser Version: iOS 13

**Comment by krsboone** [comment]
Hello,
Thank you for this feedback. I've opened the request with our product management group on your behalf - if they elect to implement the new feature, we will announce it on our changelog (https://developer.webex.com/docs/api/changelog) and for larger features, also on our blog (https://developer.webex.com/blog). Please let us know if we can help with anything else.
