### ISSUE TITLE
Create Metting from Browser SDK

### ISSUE THREAD

**Issue by athina635** [webex/webex-js-sdk#1665]
Hello, I'm new in Webex technology and i want to use the browser SDK for my node.js Application to allow people to create a meeting, start meeting and let others join this meeting as well.

I already see the documentation about that and try the simple tutorial there to join a meeting with browser SDK.

1. I want to create and start the meeting from the Browser SDK,?
2. the problem of the access token, in the documentation they said it's just for test purposes! how can I get my token for production purposes? cuz, every time I want to test I have to pass the new token.

**PS: I have a Pro Webex account. ane I want to use it** 

Hope you can help me.

**Comment by taymoork2** [comment]
Go to https://developer.webex.com/my-apps and create a new integration, from there you'll get a token used for production purposes

**Comment by athina635** [comment]
@taymoork2  what about this:

> Hello, I'm new in Webex technology and i want to use the browser SDK for my node.js Application to allow people to create a meeting, start meeting and let others join this meeting as well.

**Comment by taymoork2** [comment]
Meetings uses WebRTC which are browser provided APIs not available on node

**Comment by lalli-flores** [comment]
@athina635, as @taymoork2 mentioned, Meetings are a _browser_ feature only and will not work on a pure Node.js environment as [WebRTC](https://webrtc.org) is a browser standard.

**Comment by lakkiniCom** [comment]
@lalli-flores yes and that what i need a similar feature as webRTC with the WebEx API. I'm not talking about a pure nodejs app.

is that a possibility to integrate the SDK on my web APP ? as i did with webRTC?
thank you.

**Comment by athina635** [comment]
@lalli-flores yes and that what i need a similar feature as webRTC with the WebEx API. I'm not talking about a pure nodejs app.

is that a possibility to integrate the SDK on my web APP ? as i did with webRTC?
thank you.

**Comment by lalli-flores** [comment]
@athina635, if you haven't already, please reach out to support for help: https://developer.webex.com/support
