### ISSUE TITLE
"media:stopped" not called as expected

### ISSUE THREAD

**Issue by TdoubleG** [webex/webex-js-sdk#1683]
## Expected Behavior

As the event indicated I expected that the "media:stopped" event is fired even when e.g. the moderator ended the remote share of a meeting.
Despite of this behaviour it confuses me, that the event "media:stopped" is called, when the meeting is ended by the moderator.
If I log the "media" payload it logs "local" and "localShare". This seems to be wrong to me, because the remotes (audio, video, share) should be logged either.

## Current Behavior

After e.g. the moderator ended sharing his screen the event "media:stopped" is not called.

## Possible Solution (we welcome any logical suggestion)

The "media:stopped" event should be fired when the moderator stops the remote share.

## Steps to Reproduce

I used the example from the docs.

## Environment Details

* SDK Version 1.8.x
* Node/Browser Version 10.16.3
* NPM Version 6.14.5

**Comment by adamweeks** [comment]
Please contact developer support at https://developer.webex.com/support for further assistance with this issue.
