### ISSUE TITLE
Unable to retrieve any memberships

### ISSUE THREAD

**Issue by JCSynthTux** [webex/webex-js-sdk#1740]
## Expected Behavior
TeamMemberships.list should return memberships of token owner or atleast an error.

## Current Behavior
We are currently only getting `Page {}` without any status code. This also happens when trying to get room memberships and other memberships. 
Creating teams and rooms via SDK works fine.
Getting memberships through developer.webex works fine and as expected. 

## Steps to Reproduce
Token and the initial process work as expected.
This is the exact code we are using:
```
webex.teams.list({})
    .then(teams => {
      console.log(teams);
    })
    .catch(err => console.log(err));
```

## Environment Details
* SDK Version = 1.80.231
* Node Version = v8.12.0
* NPM Version = 6.9.0

**Comment by adamweeks** [comment]
Please contact developer support at https://developer.webex.com/support for further assistance with this issue.
