### ISSUE TITLE
Configurable log file/buffer log level

### ISSUE THREAD

**Issue by glenatwork** [webex/webex-js-sdk#1782]
## Expected Behavior

Offer a configuration setting, such as "bufferLogLevel" that allows setting what level of logs are sent to the buffer/file logs.

## Current Behavior

The level is currently hard-coded to info:
  shouldBuffer(level) {
    return precedence[level] <= precedence.info;
  },

## Possible Solution (we welcome any logical suggestion)

It should be as simple as something like:

```
    return precedence[level] <= (this.config.bufferLogLevel ? precedence[this.config.bufferLogLevel] : precedence.info);
```

## Environment Details

There is no way to set the buffer log level in any environment.

**Comment by lalli-flores** [comment]
Issue fixed by PR https://github.com/webex/webex-js-sdk/pull/1792. Thank you, @glenatwork
