### ISSUE TITLE
meetings.getAllMeetings method only returns open/active meetings

### ISSUE THREAD

**Issue by beefgrits** [webex/webex-js-sdk#1788]
## Expected Behavior
 - Method is expected to return meeting calendar entries

## Current Behavior
 - Response is empty unless a meeting is currently active

## Possible Solution (we welcome any logical suggestion)
 - failback on GET /meetings REST method

## Steps to Reproduce
1. call meetings.getAllMeetings method with a search string that includes one or more scheduled meetings that are not currently open.

## Environment Details
latest

**Comment by arun3528** [comment]
Get all meeting only shows up meeting which is about to start or started . If you need scheduled meetings check for calendar plugin which is internal currently . There is plan to expose it on meetings object as well

**Comment by beefgrits** [comment]
Thanks for validating, I was relaying this from other developer. Please consider updating related documentation that quotes this method as returning, "Object: All active **and scheduled** meetings."

**Comment by lalli-flores** [comment]
@beefgrits Updated doc to reflect the actual return value. It should be reflected in the docs next time there's a release of the SDK
