### ISSUE TITLE
media:stopped payload is 'remote' instead of remoteAudio/remoteVideo

### ISSUE THREAD

**Issue by zmeyc** [webex/webex-js-sdk#1832]
## Expected Behavior

According to docs and samples `media:stopped` event is expected to contain type `remoteAudio` or `remoteVideo` in payload depending on what stream is being stopped.

## Current Behavior

Only one event `remote` (EVENT_TYPES.REMOTE) is returned.

## Possible Solution (we welcome any logical suggestion)

If both audio and video streams should be removed on `media:stopped remote` event, docs and samples need to be updated.

## Steps to Reproduce

Add to any of the samples:
```
  meeting.on('media:stopped', async (media: any) => {
    console.log('Media stopped:', media)
  })
```

## Environment Details

* SDK Version: 1.88.1
* Node/Browser Version: v12.11.1 / Google Chrome
* NPM Version n/a

**Comment by lalli-flores** [comment]
Fixed by https://github.com/webex/webex-js-sdk/pull/1839
