### ISSUE TITLE
StopScreenshare is event is not invoked when Screenshare is stopped on other side 

### ISSUE THREAD

**Issue by nikhilo6july** [webex/webex-js-sdk#1919]
When someone stops sharing screen another side, my side those events are not called. which based on documentation, it should be invoked. I tried with multiple console logs and media. It doesn't work

![image](https://user-images.githubusercontent.com/34338296/97653217-35cfdc80-1a9b-11eb-9bc8-9d399fd71a0d.png)

Any other way to know when the screen share is stopped by other participant or to know if screen  is being shared or stopped during the meeting.

**Comment by adamweeks** [comment]
Thanks for reporting this issue, unfortunately issues on github are not tracked. Please contact developer support to open an issue with the engineering team: https://developer.webex.com/support
