### ISSUE TITLE
SDK initialization is taking time

### ISSUE THREAD

**Issue by rajatsdp** [webex/webex-js-sdk#2027]
We are using this SDK for Chat functionality and we are seeing a delay of ~15 sec in initialisation of the SDK.
In Network, we see multiple API calls to **catalog?format=hostmap** endpoint taking ~5sec.
I have attached the screenshot of the Network tab having information on the time taken by multiple API calls made by SDK.

Can we somehow optimise this initialisation delay ?
<img width="1662" alt="Screenshot 2021-03-09 at 12 14 21 PM" src="https://user-images.githubusercontent.com/5759284/110430919-15f89700-80d3-11eb-832b-00036fe20b3d.png">

**Comment by adamweeks** [comment]
Please utilize developer support for opening issues as described https://github.com/webex/webex-js-sdk/issues/new/choose
