### ISSUE TITLE
Support for cross-region boards

### ISSUE THREAD

**Issue by pcl** [webex/webex-js-sdk#2155]
Currently, webex-js-sdk doesn't properly support cross-region boards. Let's fix that.

Most recently, this manifests in realtime.js:115, which does not propagate the board channel URL (and thus the board channel cluster) to the board registration call, resulting in an attempted registration in the wrong cluster.

https://github.com/webex/webex-js-sdk/blob/097f11497e6befaf7da918ebe925b8be8172ad8c/packages/node_modules/%40webex/internal-plugin-board/src/realtime.js#L97

**Comment by jbenyovs** [comment]
@pcl can you please provide some more details and concrete examples about this issue showing the expected and actual cluster? Can you also share the board channel URL you mentioned? Any steps we can use to reproduce this? I assume it is reproducible with the https://js.samples.s4d.io/browser-plugin-meetings/ demo here, but can you confirm?

**Comment by pcl** [comment]
I haven't tried to reproduce the bug in your sample app, but it's probably reproducible there.

Here are two different board URLs:

https://board-a.wbx2.com/board/api/v1/channels/16321ab0-00d1-11ec-bca4-e56fcbadda24
https://board-k.wbx2.com/board/api/v1/channels/3e9e50a0-ff63-11eb-b573-eda7098f33a9

A user homed in cluster `a` will not be able to call `register()` on the `board-k` URL, since the registration has to happen against `board-k.wbx2.com`.

**Comment by pcl** [comment]
Also, fyi, the API call you're using has been deprecated. I had the board team turn it back on, so that at least the client sorta works, but you should not expect this API to be around forever.

https://sqbu-github.cisco.com/WebExSquared/board/blob/master/server/src/main/java/com/cisco/wx2/board/server/BoardController.java#L81

**Comment by jbenyovs** [comment]
@pcl thanks, I have reached out to engineering to check your commit and reply to this.

**Comment by pcl** [comment]
Great, thanks.

I see that some checks failed, but I can't see why. Can you post details here? I don't intend to give CircleCI access to my private repositories...

**Comment by pcl** [comment]
Oh and also -- the changes in the related PR are working great in our downstream codebase.

**Comment by jbenyovs** [comment]
@pcl we received a feedback from engineering management and according to them this is not a bug, it's an enhancement request. Additionally, board plugin is internal and only meant to be used by the web app team.

**Comment by pcl** [comment]
Ok cool. Be sure to let engineering management know about the bug in the
web client, and please send me the jira for the corresponding filed bug.
