### ISSUE TITLE
Event on auth expiry / failure

### ISSUE THREAD

**Issue by kahole** [webex/webex-js-sdk#2175]
Feature request.
It would be useful to get an event when a request fails on auth.
It would fire off when:
1. The auth intercepter receives a 401, and it's unable to automatically re-auth
2. Auth failure / expiry is detected in any other way

This way we don't have to handle "bad auth" for every sdk method call and request.

**Comment by ralagana** [comment]
Hello, you can create a feature request here: https://ciscocollaboration.ideas.aha.io/ . PMs can then check it there and reply accordingly. Thanks
