### ISSUE TITLE
Webex Calling SDK CORS Issue

### ISSUE THREAD

**Issue by rajravat** [webex/webex-js-sdk#3428]
I'm trying to follow the guide here:
https://github.com/webex/webex-js-sdk/wiki/Quickstart-Guide-(Calling)#calling-configuration

to try out the webex calling api, using the script specified on there:
<script src='https://unpkg.com/webex@2.60.0-next.2/umd/calling.min.js'></script>

However, when the page is initialising, i am receiving a cors error for requests going to the following url:
https://mobius-eu-central-1.prod.infra.webex.com/api/v1/calling/web/myip

I dont see any mention of having to set up cors, so im a bit lost as to where to go next, is someone able to help?

console output from Chrome:
![image](https://github.com/webex/webex-js-sdk/assets/25839791/55a70789-f25f-4a9d-bc75-7900162a1fc4)

**Comment by mpalkovi** [comment]
Hello, localhost will not be allowed by the host mentioned in the error. As a workaround please use chrome with the disable-web-security mode while testing this with localhost.

**Comment by rajravat** [comment]
Thank you that worked a treat, when we eventually deploy onto a test environment, does the host need to be on a publicly accessible domain? or would it work on with a private dns zone?

**Comment by jbenyovs** [comment]
@rajravat  let me check that internally and have that confirmed for you. Will let you know.

**Comment by jbenyovs** [comment]
@rajravat engineering confirmed that as long as the network's firewalls allow the mercury socket to be established, this should be ok. Notifications for the SDK arrive on the socket so if this isn't allowed then the SDK might register but will not be able to place and receive calls.

**Comment by rajravat** [comment]
Thanks
