### ISSUE TITLE
Webex JS SDK Calling - Devices not being unregistered

### ISSUE THREAD

**Issue by rajravat** [webex/webex-js-sdk#3447]
We are currently using the webex js sdk calling features in a solution. Some of the devs occasionally see an error stating that "User has excessive device registrations".  We are unregistering the line by calling line.deregister() method as per the Kitchen Sink example app and we see the line.on("unregistrated") callback fire successfully, but we still continue to see this error.

What i have observed is that calling this endpoint shows devices that are registered when the user logs in:

https://wdm-k.wbx2.com/wdm/api/v1/devices/

however, the devices do not get removed from here when line.deregister() is called, is this a bug? They do eventually disappear from that endpoint after a few days, but it doesn't seem to be anything that we have control over, is anyone able to advise if this is a bug and/or if there are other things we can do to prevent getting the "excessive device registrations" error?

We are using the 3.0.0-next-1 SDK via unpkg from https://unpkg.com/webex@3.0.0-next.1/umd/calling.min.js

I am also aware that we can log into https://idbroker-eu.webex.com/idb/profile#/tokens and click "end session", but this only seems to be related to tokens, not devices.

Thanks

**Comment by jbenyovs** [comment]
@rajravat can you please explain a bit more about your authorization flow? How many devices are you registering? Is it possible that unregister() is not part of your regular flow, meaning that you only call that function if you are seeing the error "User has excessive device registrations"? 
Note that it is good practice to unregister the device as soon as it is not needed anymore. Every registered device counts against your limit of 750 tokens. The https://idbroker-eu.webex.com/idb/profile#/tokens link is one way of de-registering unused devices, another one is to use this API https://developer.webex.com/docs/api/v1/authorizations .

**Comment by rajravat** [comment]
A single user logs into a desktop application (we are using the Edge WebView2 embedded into the app). This is done via auth code flow as explained on the cisco dev docs, we get an auth code and exchange it for an access token.

We then call Calling.init and pass the credentials through as can be seen in the code below:

![image](https://github.com/webex/webex-js-sdk/assets/25839791/4303a006-1833-4a28-abb5-d1e62b2a1054)

![image](https://github.com/webex/webex-js-sdk/assets/25839791/30a5dd17-d5c6-4029-b6fe-14e2096d3379)

once the user has closed down the application we call line.register()
![image](https://github.com/webex/webex-js-sdk/assets/25839791/80acb037-3e4e-4481-8bfc-b92ff27fbe66)

We successfully see the "unregistered device successfully" message in the console.

however, querying the following url, we do not see the device get removed:
https://wdm-k.wbx2.com/wdm/api/v1/devices/

**Comment by jbenyovs** [comment]
@rajravat thanks for the reply. In this case we would need to dig deeper to find out why the device is not removed from the list. We would need full Console logs for that and since it might contain personal info, best would be to create a Dev Support ticket for this - https://developer.webex.com/support . Thanks

**Comment by rajravat** [comment]
Thanks,

you can reproduce the same problem using the sample kitchen sink app website:

https://webex.github.io/webex-js-sdk/samples/calling/

1. Put in your access token
2. Initialise calling

At this point if you perform a get request on this url (https://wdm-k.wbx2.com/wdm/api/v1/devices/), you will see the device registration it has just created.

3. Click register
4. Click unregister (which called line.deregister()

Check the url again (https://wdm-k.wbx2.com/wdm/api/v1/devices/) and you will see it has not removed any devices.

You can then press f5 and perform the same actions again and see that more and more devices just get added to the wdm url without getting removed.

I've noticed in the bot framework api, it has a function to delete all the registrations:

https://github.com/WebexCommunity/webex-node-bot-framework/blob/main/lib/websocket.js
![image](https://github.com/webex/webex-js-sdk/assets/25839791/58b0658a-12c7-4a44-84d8-d9a70a16b49e)

**Comment by jbenyovs** [comment]
@rajravat thanks for the instructions, I was able to replicate this on the Calling Kitchensink app. We are working on it with the SDK engineering team and will let you know.

**Comment by jbenyovs** [comment]
@rajravat short update:
this is working as designed right now.

There are 2 device registrations that occur in the Calling SDK.

WDM registration to create a web device in Webex.
Registration with Webex Calling which creates the registration for the line.
The line.deregister() does not unregister the WDM. WDM device deletion is a different method which we have not exposed on the Calling SDK.
We will investigate our code and check if we can trigger a WDM deletion from the Calling SDK method.

**Comment by rajravat** [comment]
Thanks for the update

**Comment by arun3528** [comment]
cc @sreenara  , delete on WDM 

> Thanks,
> 
> you can reproduce the same problem using the sample kitchen sink app website:
> 
> https://webex.github.io/webex-js-sdk/samples/calling/
> 
> 1. Put in your access token
> 2. Initialise calling
> 
> At this point if you perform a get request on this url (https://wdm-k.wbx2.com/wdm/api/v1/devices/), you will see the device registration it has just created.
> 
> 3. Click register
> 4. Click unregister (which called line.deregister()
> 
> Check the url again (https://wdm-k.wbx2.com/wdm/api/v1/devices/) and you will see it has not removed any devices.
> 
> You can then press f5 and perform the same actions again and see that more and more devices just get added to the wdm url without getting removed.
> 
> I've noticed in the bot framework api, it has a function to delete all the registrations:
> 
> https://github.com/WebexCommunity/webex-node-bot-framework/blob/main/lib/websocket.js ![image](https://private-user-images.githubusercontent.com/25839791/314106577-58b0658a-12c7-4a44-84d8-d9a70a16b49e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MDExNTAsIm5iZiI6MTcxNDQwMDg1MCwicGF0aCI6Ii8yNTgzOTc5MS8zMTQxMDY1NzctNThiMDY1OGEtMTJjNy00YTQ0LTg0ZDgtZDlhNzBhMTZiNDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE0MjczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMGIwY2NkMjBkNmE2NjA0MjVlOGUwNTcwNWJkY2UzMThhNGYwMGQzYTQ1YWVhY2VmMWQ5ZWY2ZGFhNTUzYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iBvKd9siuKoGjDrb8PQowI4p9Xs0hsqNoWJ-kyfBFfk)

We will need to expose this as part of webex object i think , @jbenyovs

**Comment by JiandongRuan** [comment]
BTW, the same issue can be reproed on Webex JS SDK Meeting as well. You can repro it using the meeting kitchen app https://webex.github.io/webex-js-sdk/samples/browser-plugin-meetings/

**Comment by jbenyovs** [comment]
@rajravat this issue is fixed and is available as part of webex@3.0.0-next.31 

So, instead of line.deregister() you can start calling the method calling.deregister() which will take care of deregistering all the active lines and also deregistering the WDM devices. If you do that, you will not see the error anymore. Please try out and see if it works for you too.

**Comment by rajravat** [comment]
Thank you
