### ISSUE TITLE
Is there flag to know if a person can be muted remotely or not?

### ISSUE THREAD

**Issue by lak-16** [webex/webex-js-sdk#3578]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to find if a remote user can be muted or not. iOS sdk has a method isAudioMutedControlled. It will be nice to have one in web sdk too.

Also can I mute all and unmute all?

**Comment by sreenara** [comment]
@lak-16 Yes the `member` object inside a `meeting` has an attribute called `isMutable`. This boolean field can be used to determine if a participant can be muted or not.
https://github.com/webex/webex-js-sdk/blob/next/packages/%40webex/plugin-meetings/src/member/index.ts#L26

Mute/Unmute All is not available yet and we will create an enhancement ticket on our side for this.
