### ISSUE TITLE
PTZ Support in 3.0 sdk

### ISSUE THREAD

**Issue by lak-16** [webex/webex-js-sdk#3614]
**Is your feature request related to a problem? Please describe.**
In 2.0 SDK I can do getUserMedia and send that stream to sdk. So, I have full control to apply pan/tilt/zoom constraints on video stream and apply constrains when user do pan/tilt/zoom.

In 3.0 SDK am dependent on sdk to generate the stream and which doesn't take ptz constraints.

**Describe the solution you'd like**
Now a days most of the integrated cameras and USB cameras supports the PTZ and also browsers. So, please add support for PTZ https://ptz.glitch.me/ 

We will not be able to upgrade and release it to customers until PTZ feature is supported as already our existing customers using this feature.

**Describe alternatives you've considered**
Alternative is, sdk should take the stream what clients sends same as 2.0.

**Comment by pumoru** [comment]
Hello,

Thank you for contacting developer support. The  Browser SDK primarily focuses on audio and video conferencing capabilities and does not offer built-in support for PTZ (Pan-Tilt-Zoom) camera control.

Thank you.

**Comment by lak-16** [comment]
Are there any plans to do it in future?

**Comment by sreenara** [comment]
@lak-16 have you tried to do a `getUserMedia` to get the MediaStream with the constraints you're looking for and then do the following?
```
const stream = navigator.mediaDevices.getUserMedia(videoConstraints);
const cameraStream = new LocalCameraStream(stream);
```
`LocalCameraStream` is a class available from `@webex/media-helpers`

**Comment by sreenara** [comment]
@lak-16 I've spoken to the media team that owns the code for Stream classes. There will be a way to pass additional constraints to the stream classes soon. I will provide some update on the timelines once I have them.

**Comment by lak-16** [comment]
@sreenara am able to use webex.meetings.mediaHelpers.createCameraStream() with PTZ constraints. Once I stream is created am taking outputStream apply PTZ on that stream. It works without any issue. 

Closing this ticket
