### ISSUE TITLE
add in-memory storage fallback for localStorage and localForage

### ISSUE THREAD

**Issue by aimeex3** [webex/webex-js-sdk#484]
some browsers, like private safari browser, does not work with localStorage/localForage. In these scenarios, they should fallback to in-memory storage

**Comment by aimeex3** [comment]
same with sessionStorage

**Comment by olivierproffit** [comment]
@aimeex3 we don't support Safari yet so do you still need it? Can you share your use case? Please ping me over Webex Teams to discuss your feature requests since I don't have your email ?
