### ISSUE TITLE
canDownscope returns incorrect result

### ISSUE THREAD

**Issue by tshmukle** [webex/webex-js-sdk#587]
While initializing spark client, we see wrong Exception that unable  to downscope the token, since canDownscope for token is invoked before the constructor for ciscospark object is invoked , where the clientId and token set. Once ciscospark object is initialized, canDownscope is invoked again, but getting results from cache, even though the config credentials of the object were set/changed. We feel like there is a possibility for timing issue there, because  it seems working as expected from time to time -- not 100% sure, though.
Here is our code 
require('@ciscospark/plugin-encryption');
const CiscoSpark = require('@ciscospark/spark-core').default;
...
// >>>>> canDownscope is called here and set to false
const spark = new CiscoSpark({
			  credentials: {
			    authorization: kmsToken
			  },
              config: {
				credentials: {
					client_id: clientId
				}
			}
			});
//>>> canDownscope is called again, but just gets "false" from cache instead of executing the method. Should return true and sometimes it does, but not always

**Comment by ianwremmel** [comment]
This is because `config` isn't available until half a tick after we try to read it; the unit tests didn't catch this because `MockSpark` doesn't initialize in quite the same way as `Spark`. Now that we broadcast a change event down the tree, maybe adding `config` to `deps` will be enough. Investigating.

**Comment by ianwremmel** [comment]
This is no longer an issue, right? I'm pretty sure you or someone on your team has told me that you've been letting the sdk handle downscoping.

**Comment by tshmukle** [comment]
That is correct, we , ContextService, handling downscoping ourselves now, but this bug remains true for someone, who would not.

Therefore, I am not sure if the argument to close this bug is valid :)


Thanks,

Tanya

________________________________
