### ISSUE TITLE
Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by ipstas** [webex/webex-js-sdk#655]
I am trying to use it with meteor. 
Got it with 
`const ciscospark = require('ciscospark');`
However it seems that 'rooms' is not defined there.

My guess it is because of meteor and specific node version 4.8.4? Can somebody confirm please? Am I out of luck and SDK can not be used with meteor?

**Comment by ianwremmel** [comment]
Hi @ipstas. You'll want to use node 6 or later. 4 *may* work, but we're only testing against the current [LTS](https://github.com/nodejs/LTS).

With the release of 1.0, the package returns a constructor, not an instance, so you'll want to change `const ciscospark = require('ciscospark');` to
```js
const CiscoSpark = require('ciscospark');
const ciscospark = CiscoSpark.init();
```
